import {
	AdditionWithRegroupingPropsSchema,
	AngleTypeDiagramPropsSchema,
	AreaModelMultiplicationPropsSchema,
	BarChartPropsSchema,
	BoxGridPropsSchema,
	ClockDiagramPropsSchema,
	CustomPolygonDiagramPropsSchema,
	DataTablePropsSchema,
	DivisionAreaDiagramPropsSchema,
	DivisionModelDiagramPropsSchema,
	EquivalentFractionModelPropsSchema,
	FactorizationDiagramPropsSchema,
	FractionFrequencyPlotPropsSchema,
	FractionModelDiagramPropsSchema,
	FractionMultiplicationModelPropsSchema,
	FractionNumberLinePropsSchema,
	FractionSumDiagramPropsSchema,
	GeometricPrimitiveDiagramPropsSchema,
	LabeledRectangleDiagramPropsSchema,
	NPolygonPropsSchema,
	NumberLinePropsSchema,
	NumberLineWithActionPropsSchema,
	PatternDiagramPropsSchema,
	ProtractorAngleDiagramPropsSchema,
	QuantityFractionalDiagramPropsSchema,
	SimpleArrowPropsSchema,
	SubtractionWithRegroupingPropsSchema,
	TapeDiagramPropsSchema,
	TransformationDiagramPropsSchema,
	VectorDiagramPropsSchema,
	VerticalArithmeticSetupPropsSchema,
	WheelDiagramPropsSchema
} from "../registry"

export const fourthGradeMathCollection = {
	name: "fourth-grade-math",
	schemas: {
		clockDiagram: ClockDiagramPropsSchema,
		wheelDiagram: WheelDiagramPropsSchema,
		geometricPrimitiveDiagram: GeometricPrimitiveDiagramPropsSchema,
		angleTypeDiagram: AngleTypeDiagramPropsSchema,
		dataTable: DataTablePropsSchema,
		tapeDiagram: TapeDiagramPropsSchema,
		fractionModelDiagram: FractionModelDiagramPropsSchema,
		fractionSumDiagram: FractionSumDiagramPropsSchema,
		fractionMultiplicationModel: FractionMultiplicationModelPropsSchema,
		fractionFrequencyPlot: FractionFrequencyPlotPropsSchema,
		divisionAreaDiagram: DivisionAreaDiagramPropsSchema,
		divisionModelDiagram: DivisionModelDiagramPropsSchema,
		factorizationDiagram: FactorizationDiagramPropsSchema,
		numberLine: NumberLinePropsSchema,
		numberLineWithAction: NumberLineWithActionPropsSchema,
		protractorAngleDiagram: ProtractorAngleDiagramPropsSchema,
		quantityFractionalDiagram: QuantityFractionalDiagramPropsSchema,
		additionWithRegrouping: AdditionWithRegroupingPropsSchema,
		subtractionWithRegrouping: SubtractionWithRegroupingPropsSchema,
		verticalArithmeticSetup: VerticalArithmeticSetupPropsSchema,
		fractionNumberLine: FractionNumberLinePropsSchema,
		boxGrid: BoxGridPropsSchema,
		barChart: BarChartPropsSchema,
		equivalentFractionModel: EquivalentFractionModelPropsSchema,
		areaModelMultiplication: AreaModelMultiplicationPropsSchema,
		simpleArrow: SimpleArrowPropsSchema,
		vectorDiagram: VectorDiagramPropsSchema,
		nPolygon: NPolygonPropsSchema,
		patternDiagram: PatternDiagramPropsSchema,
		transformationDiagram: TransformationDiagramPropsSchema,
		labeledRectangleDiagram: LabeledRectangleDiagramPropsSchema,
		customPolygonDiagram: CustomPolygonDiagramPropsSchema
	},
	widgetTypeKeys: [
		"clockDiagram",
		"wheelDiagram",
		"geometricPrimitiveDiagram",
		"angleTypeDiagram",
		"dataTable",
		"tapeDiagram",
		"fractionModelDiagram",
		"fractionSumDiagram",
		"fractionMultiplicationModel",
		"fractionFrequencyPlot",
		"divisionAreaDiagram",
		"divisionModelDiagram",
		"factorizationDiagram",
		"numberLine",
		"numberLineWithAction",
		"protractorAngleDiagram",
		"quantityFractionalDiagram",
		"additionWithRegrouping",
		"subtractionWithRegrouping",
		"verticalArithmeticSetup",
		"fractionNumberLine",
		"boxGrid",
		"barChart",
		"equivalentFractionModel",
		"areaModelMultiplication",
		"simpleArrow",
		"vectorDiagram",
		"nPolygon",
		"patternDiagram",
		"transformationDiagram",
		"labeledRectangleDiagram",
		"customPolygonDiagram"
	] as const
} as const
