import {
	AbsoluteValueNumberLinePropsSchema,
	AngleDiagramPropsSchema,
	BarChartPropsSchema,
	BoxGridPropsSchema,
	BoxPlotPropsSchema,
	CircleDiagramPropsSchema,
	CompositeShapeDiagramPropsSchema,
	CoordinatePlaneComprehensivePropsSchema,
	DataTablePropsSchema,
	DiscreteObjectRatioDiagramPropsSchema,
	DistanceFormulaGraphPropsSchema,
	DotPlotPropsSchema,
	DoubleNumberLinePropsSchema,
	EmojiImagePropsSchema,
	FigureComparisonDiagramPropsSchema,
	FractionNumberLinePropsSchema,
	FunctionPlotGraphPropsSchema,
	GeometricSolidDiagramPropsSchema,
	HangerDiagramPropsSchema,
	HistogramPropsSchema,
	InequalityNumberLinePropsSchema,
	IntegerChipModelPropsSchema,
	LineEquationGraphPropsSchema,
	MarbleDiagramPropsSchema,
	NPolygonPropsSchema,
	NumberLineForOppositesPropsSchema,
	NumberLinePropsSchema,
	NumberLineWithActionPropsSchema,
	NumberLineWithFractionGroupsPropsSchema,
	NumberSetDiagramPropsSchema,
	ParallelogramTrapezoidDiagramPropsSchema,
	PartitionedShapePropsSchema,
	PentagonIntersectionDiagramPropsSchema,
	PictographPropsSchema,
	PointPlotGraphPropsSchema,
	PolygonGraphPropsSchema,
	PolyhedronDiagramPropsSchema,
	PolyhedronNetDiagramPropsSchema,
	ProbabilitySpinnerPropsSchema,
	PythagoreanProofDiagramPropsSchema,
	RatioBoxDiagramPropsSchema,
	RectangularFrameDiagramPropsSchema,
	ScaleCopiesSliderPropsSchema,
	ScatterPlotPropsSchema,
	ShapeTransformationGraphPropsSchema,
	StackedItemsDiagramPropsSchema,
	TapeDiagramPropsSchema,
	ThreeDIntersectionDiagramPropsSchema,
	TransformationDiagramPropsSchema,
	TreeDiagramPropsSchema,
	TriangleDiagramPropsSchema,
	UnitBlockDiagramPropsSchema,
	VennDiagramPropsSchema,
	VerticalArithmeticSetupPropsSchema
} from "../registry"

export const mathCoreCollection = {
	name: "math-core",
	schemas: {
		threeDIntersectionDiagram: ThreeDIntersectionDiagramPropsSchema,
		absoluteValueNumberLine: AbsoluteValueNumberLinePropsSchema,
		angleDiagram: AngleDiagramPropsSchema,
		barChart: BarChartPropsSchema,
		boxGrid: BoxGridPropsSchema,
		boxPlot: BoxPlotPropsSchema,
		circleDiagram: CircleDiagramPropsSchema,
		compositeShapeDiagram: CompositeShapeDiagramPropsSchema,
		coordinatePlane: CoordinatePlaneComprehensivePropsSchema,
		dataTable: DataTablePropsSchema,
		discreteObjectRatioDiagram: DiscreteObjectRatioDiagramPropsSchema,
		distanceFormulaGraph: DistanceFormulaGraphPropsSchema,
		dotPlot: DotPlotPropsSchema,
		doubleNumberLine: DoubleNumberLinePropsSchema,
		emojiImage: EmojiImagePropsSchema,
		figureComparisonDiagram: FigureComparisonDiagramPropsSchema,
		fractionNumberLine: FractionNumberLinePropsSchema,
		functionPlotGraph: FunctionPlotGraphPropsSchema,
		geometricSolidDiagram: GeometricSolidDiagramPropsSchema,
		hangerDiagram: HangerDiagramPropsSchema,
		histogram: HistogramPropsSchema,
		inequalityNumberLine: InequalityNumberLinePropsSchema,
		marbleDiagram: MarbleDiagramPropsSchema,
		lineEquationGraph: LineEquationGraphPropsSchema,
		numberLine: NumberLinePropsSchema,
		numberLineForOpposites: NumberLineForOppositesPropsSchema,
		numberLineWithAction: NumberLineWithActionPropsSchema,
		numberLineWithFractionGroups: NumberLineWithFractionGroupsPropsSchema,
		numberSetDiagram: NumberSetDiagramPropsSchema,
		parallelogramTrapezoidDiagram: ParallelogramTrapezoidDiagramPropsSchema,
		partitionedShape: PartitionedShapePropsSchema,
		pentagonIntersectionDiagram: PentagonIntersectionDiagramPropsSchema,
		pictograph: PictographPropsSchema,
		integerChipModel: IntegerChipModelPropsSchema,
		pointPlotGraph: PointPlotGraphPropsSchema,
		polygonGraph: PolygonGraphPropsSchema,
		polyhedronDiagram: PolyhedronDiagramPropsSchema,
		polyhedronNetDiagram: PolyhedronNetDiagramPropsSchema,
		probabilitySpinner: ProbabilitySpinnerPropsSchema,
		pythagoreanProofDiagram: PythagoreanProofDiagramPropsSchema,
		ratioBoxDiagram: RatioBoxDiagramPropsSchema,
		rectangularFrameDiagram: RectangularFrameDiagramPropsSchema,
		scaleCopiesSlider: ScaleCopiesSliderPropsSchema,
		scatterPlot: ScatterPlotPropsSchema,
		shapeTransformationGraph: ShapeTransformationGraphPropsSchema,
		stackedItemsDiagram: StackedItemsDiagramPropsSchema,
		tapeDiagram: TapeDiagramPropsSchema,
		transformationDiagram: TransformationDiagramPropsSchema,
		treeDiagram: TreeDiagramPropsSchema,
		triangleDiagram: TriangleDiagramPropsSchema,
		unitBlockDiagram: UnitBlockDiagramPropsSchema,
		vennDiagram: VennDiagramPropsSchema,
		verticalArithmeticSetup: VerticalArithmeticSetupPropsSchema,
		nPolygon: NPolygonPropsSchema
	},
	widgetTypeKeys: [
		"threeDIntersectionDiagram",
		"absoluteValueNumberLine",
		"angleDiagram",
		"barChart",
		"boxGrid",
		"boxPlot",
		"circleDiagram",
		"compositeShapeDiagram",
		"coordinatePlane",
		"dataTable",
		"discreteObjectRatioDiagram",
		"distanceFormulaGraph",
		"dotPlot",
		"doubleNumberLine",
		"emojiImage",
		"figureComparisonDiagram",
		"fractionNumberLine",
		"functionPlotGraph",
		"geometricSolidDiagram",
		"hangerDiagram",
		"histogram",
		"inequalityNumberLine",
		"marbleDiagram",
		"lineEquationGraph",
		"numberLine",
		"numberLineForOpposites",
		"numberLineWithAction",
		"numberLineWithFractionGroups",
		"numberSetDiagram",
		"parallelogramTrapezoidDiagram",
		"partitionedShape",
		"pentagonIntersectionDiagram",
		"pictograph",
		"integerChipModel",
		"pointPlotGraph",
		"polygonGraph",
		"polyhedronDiagram",
		"polyhedronNetDiagram",
		"probabilitySpinner",
		"pythagoreanProofDiagram",
		"ratioBoxDiagram",
		"rectangularFrameDiagram",
		"scaleCopiesSlider",
		"scatterPlot",
		"shapeTransformationGraph",
		"stackedItemsDiagram",
		"tapeDiagram",
		"transformationDiagram",
		"treeDiagram",
		"triangleDiagram",
		"unitBlockDiagram",
		"vennDiagram",
		"verticalArithmeticSetup",
		"nPolygon"
	] as const
} as const
